import logging
from pathlib import Path
from PIL import Image
from fpdf import FPDF
from app.config import settings
from app.models import ComicLayout

logger = logging.getLogger("comiccraft.exporters")


def clean_pdf_text(text: str) -> str:
    """Sanitizes text by replacing common unicode characters with Latin-1 equivalents."""
    if not text:
        return ""
    replacements = {
        "\u2022": "-",
        "\u2013": "-",
        "\u2014": "--",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2026": "...",
        "\u00a0": " ",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", "replace").decode("latin-1")


class ComicPDF(FPDF):
    """Custom FPDF2 subclass with comic-themed header, footer, and styling."""

    def __init__(self, title_text: str = "ComicCraft AI Comic"):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.doc_title = clean_pdf_text(title_text)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(120, 120, 130)
        self.cell(0, 8, "COMICCRAFT  |  AI COMIC STORY CREATOR", align="L", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(220, 220, 230)
        self.line(10, 18, 200, 18)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 160)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  -  Generated by ComicCraft", align="C")


def resolve_image_disk_path(image_path: str) -> str | None:
    """Resolves web or relative image URL to an absolute disk path."""
    if not image_path:
        return None
    clean_rel = image_path.lstrip("/")
    possible_path = settings.base_dir / clean_rel
    if possible_path.exists():
        return str(possible_path)
    if Path(image_path).exists():
        return str(Path(image_path).resolve())
    return None


def draw_scaled_image(pdf: ComicPDF, img_path: str, max_w: float = 135, max_h: float = 105) -> float:
    """
    Renders an image centered on page, scaling proportionally to fit within max_w and max_h.
    Guarantees no overlap with surrounding text by calculating exact rendered height.
    """
    try:
        with Image.open(img_path) as im:
            orig_w, orig_h = im.size
        
        scale = min(max_w / orig_w, max_h / orig_h)
        w = orig_w * scale
        h = orig_h * scale
        x = (210 - w) / 2
        y = pdf.get_y()
        
        pdf.image(img_path, x=x, y=y, w=w, h=h)
        pdf.set_y(y + h + 6)
        return h
    except Exception as e:
        logger.error("Failed to render scaled image: %s", e)
        pdf.ln(15)
        return 15


def export_comic_to_pdf(layout: ComicLayout) -> str:
    """
    Renders a multi-page illustrated comic document from a ComicLayout object.
    Includes a cover illustration on Page 1 and cleanly spaced panels on subsequent pages.
    """
    settings.exports_dir.mkdir(parents=True, exist_ok=True)
    filename = f"{layout.comic_id}_comic.pdf"
    pdf_full_path = settings.exports_dir / filename

    pdf = ComicPDF(title_text=layout.title)
    pdf.alias_nb_pages()

    # =========================================================================
    # PAGE 1: COVER PAGE WITH HERO COVER ART
    # =========================================================================
    pdf.add_page()
    pdf.set_y(22)
    
    # Title Banner
    pdf.set_fill_color(15, 23, 42)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.multi_cell(0, 12, clean_pdf_text(layout.title).upper(), align="C", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Subtitle / Issue Tag
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(2, 132, 199)
    pdf.cell(0, 6, "OFFICIAL AI-ILLUSTRATED COMIC EDITION  -  5 SCENES", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Featured Cover Illustration (uses Panel 1 image)
    cover_img_path = None
    if layout.panels and layout.panels[0].image_path:
        cover_img_path = resolve_image_disk_path(layout.panels[0].image_path)

    if cover_img_path:
        draw_scaled_image(pdf, cover_img_path, max_w=135, max_h=95)
    else:
        pdf.ln(15)

    # Metadata Specification Box
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(203, 213, 225)
    meta_box_y = pdf.get_y()
    pdf.rect(18, meta_box_y, 174, 46, "FD")

    pdf.set_xy(24, meta_box_y + 4)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(32, 6, "Hero Character:", align="L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(50, 6, clean_pdf_text(layout.character_name), align="L")

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(24, 6, "Setting:", align="L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(50, 6, clean_pdf_text(layout.setting), align="L", new_x="LMARGIN", new_y="NEXT")

    pdf.set_x(24)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(32, 6, "Tone & Style:", align="L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(50, 6, f"{clean_pdf_text(layout.tone)} / {clean_pdf_text(layout.art_style)}", align="L")

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(24, 6, "Published:", align="L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(50, 6, clean_pdf_text(layout.created_at[:10]), align="L", new_x="LMARGIN", new_y="NEXT")

    pdf.set_x(24)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(32, 6, "Story Premise:", align="L")
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.multi_cell(125, 5, f'"{clean_pdf_text(layout.story_prompt)}"', align="L")

    # =========================================================================
    # PAGES 2 TO 6: SEQUENTIAL COMIC PANELS
    # =========================================================================
    for panel in layout.panels:
        pdf.add_page()
        pdf.set_y(22)

        # Panel Header Banner
        pdf.set_fill_color(241, 245, 249)
        pdf.set_draw_color(203, 213, 225)
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 10, f"  PANEL {panel.panel_number}: {clean_pdf_text(panel.title)}", border=1, fill=True, align="L", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # Proportional Dynamic Image Placement (No text overlap)
        img_disk_path = resolve_image_disk_path(panel.image_path)
        if img_disk_path:
            draw_scaled_image(pdf, img_disk_path, max_w=135, max_h=105)
        else:
            pdf.ln(15)

        # Caption
        if panel.caption:
            pdf.set_fill_color(240, 249, 255)
            pdf.set_draw_color(186, 230, 253)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(2, 132, 199)
            pdf.multi_cell(0, 6, f"CAPTION: {clean_pdf_text(panel.caption)}", border=1, fill=True, align="L", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(3)

        # Scene description
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.multi_cell(0, 5, f"Scene: {clean_pdf_text(panel.scene_description)}", align="L", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # Narration
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 41, 59)
        pdf.multi_cell(0, 6, f"NARRATION: {clean_pdf_text(panel.narration)}", align="L", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        # Dialogue Speech Bubble
        if panel.dialogue:
            pdf.set_fill_color(255, 251, 235)
            pdf.set_draw_color(253, 230, 138)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(180, 83, 9)
            pdf.multi_cell(0, 7, f"DIALOGUE: {clean_pdf_text(panel.dialogue)}", border=1, fill=True, align="L", new_x="LMARGIN", new_y="NEXT")

    pdf.output(str(pdf_full_path))
    logger.info("Exported comic PDF to %s", pdf_full_path)
    return f"/static/exports/{filename}"
